const fs = require('fs');
const path = require('path');
const config = require(path.resolve(__dirname) + '/../../dryfile.json');

module.exports = {
  run: function() {
    if (!config) {
      throw new Error('There must be a "dryfile.json" at the root of your project');
    }
    else if (!config.src) {
      throw new Error('"src" must be defined');
    }
    else if (!config.output) {
      throw new Error('"output" must be defined');
    }
    else if (!config.output.js) {
      throw new Error('"output.js" must be defined');
    }
    else if (!config.output.scss) {
      throw new Error('"output.scss" must be defined');
    }

    let constants;
    try {
      const constants_raw = fs.readFileSync(config.src, 'utf8');
      constants = JSON.parse(constants_raw);
    }
    catch (e) {
      throw new Error('"src" must point to a valid JSON file');
    }

    const file_top_warning = '// This file is automatically generated with Dryist; do not edit it manually.\n\n';

    let js = file_top_warning;
    Object.keys(constants).forEach(key => {
      js += `export const ${key.replace(/-/g, '_')} = ${constants[key][0]};\n`;
    });
    try {
      fs.writeFileSync(config.output.js, js);
    }
    catch (e) {
      throw new Error('"output.js" must be a valid filepath');
    }

    let scss = file_top_warning;
    Object.keys(constants).forEach(key => {
      scss += `$${key}: ${constants[key][0]}${constants[key][1]};\n`;
    });
    try {
      fs.writeFileSync(config.output.scss, scss);
    }
    catch (e) {
      throw new Error('"output.scss" must be a valid filepath');
    }
  }
}
